version: 2

defaults: &defaults
  working_directory: ~/biplab-notifier
  docker:
    - image: circleci/node:11-browsers

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install
      - run: npm run package
      - run:
          name: Run tests
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI  --code-coverage

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/biplab-notifier
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/biplab-notifier
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$GITHUB_PACKAGE_PAT" > ~/biplab-notifier/.npmrc
      - run:
          name: generate package
          command: npm run package
      - run:
          name: Publish package
          command: npm publish dist/biplab-notifier/NumbersUSA-biplab-notifier-*.tgz

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
